/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SLEECRuntimeModule extends AbstractSLEECRuntimeModule {
}
