/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class SLEECScopeProvider extends AbstractSLEECScopeProvider {

}
