/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SLEECStandaloneSetup extends SLEECStandaloneSetupGenerated {

	def static void doSetup() {
		new SLEECStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
