/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class SLEECUiModule extends AbstractSLEECUiModule {
}
