/*
 * generated by Xtext 2.25.0
 */
package circus.robocalc.sleec.ide

import circus.robocalc.sleec.SLEECRuntimeModule
import circus.robocalc.sleec.SLEECStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class SLEECIdeSetup extends SLEECStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new SLEECRuntimeModule, new SLEECIdeModule))
	}
	
}
